### PR TITLE
Support Python 3.6

### LINKED ISSUE #16: Python 3.6 compatibility
This package is not yet compatible with Python 3.6, see https://travis-ci.org/zopefoundation/zopetoolkit/jobs/173487024#L875

### PR DESCRIPTION
**Pull request by mgedmin**
Closes #16

### CODE REVIEW

**Comment by berdario** [comment]
Hi, is it possible to cut a new release with this fix? I'd rather avoid having to depend on a git revision

**Comment by mgedmin** [comment]
Gladly!

**Comment by mgedmin** [comment]
But, actually, no code changes were necessary, it was only the test suite that was broken.  The current release (4.6.0) works fine with Python 3.6, as far as I know.

**Comment by berdario** [comment]
Thank you! :+1: 

Yeah, I'm using [Nix](https://nixos.org/nix), which by default runs the test suite for packages that are being built from source (I could disable it, but that's another thing that I try to avoid)

**Pull request merged**
